// <auto-generated />
using DB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("DB.Models.Country", b =>
                {
                    b.Property<int>("CountryNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryProperty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CountryNum");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryNum = 1,
                            CountryName = "테라노스(흙의 나라)",
                            CountryProperty = "거대한 산맥과 광활한 평야 지형\n자원이 풍부하지만 환경은 거칠고 건조함\n지진 및 지열 활동이 활발함"
                        },
                        new
                        {
                            CountryNum = 2,
                            CountryName = "아쿠아리스(물의 나라)",
                            CountryProperty = "전체 표면의 95%가 바다로 덮여 있음\n기후가 온화하나 폭풍이 자주 발생\n 수중 생명체와 해양 자원 풍부"
                        },
                        new
                        {
                            CountryNum = 3,
                            CountryName = "실피(바람의 나라)",
                            CountryProperty = "대기 밀도가 낮고, 바람이 극도로 강함\n구름이 낮게 깔려 있고, 수증기 성분이 높음\n부유식 생물과 공중 섬이 존재"
                        },
                        new
                        {
                            CountryNum = 4,
                            CountryName = "인페르나(불의 나라)",
                            CountryProperty = "활화산과 용암 지대가 곳곳에 분포\n낮은 대기 안정성, 높은 복사열\n강한 자기장과 고온 생물체 서식"
                        },
                        new
                        {
                            CountryNum = 5,
                            CountryName = "몯도샤인",
                            CountryProperty = "제5원소를 만들어낸 고대 기술 문명 행성\n 제4원소의 조합을 통해 만들어진 재료와 제5원소를 활성화할 수 있는 에너지 전송 탑이 존재.\n자원들은 이 탑을 통해 실체화 시킬 수 있다."
                        },
                        new
                        {
                            CountryNum = 6,
                            CountryName = "릴리",
                            CountryProperty = "제5원소의 결정체이자 생명과 우주의 균형을 지키는 존재\n제4원소의 재료를 통해 필요한 물질을 조합할 수 있는 공간.\n릴리는 물리적 행성처럼 보이지만, 4가지 원소들을 조합할 수 있는 물건에 지나지 않음"
                        });
                });

            modelBuilder.Entity("DB.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description_I")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientNum");

                    b.HasIndex("CountryNum");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            IngredientNum = 1,
                            CountryNum = 0,
                            Description_I = "무기 제작에 사용되는 고강도 금속 원석",
                            IngredientName = "암철석"
                        },
                        new
                        {
                            IngredientNum = 2,
                            CountryNum = 0,
                            Description_I = "고열을 견디는 귀금속, 전도성이 뛰어남",
                            IngredientName = "진토금"
                        },
                        new
                        {
                            IngredientNum = 3,
                            CountryNum = 0,
                            Description_I = "고대 생물의 화석에서 채굴되는 결정성 자원",
                            IngredientName = "석기정"
                        },
                        new
                        {
                            IngredientNum = 4,
                            CountryNum = 0,
                            Description_I = "깊은 해저에서 추출되는 희귀 금속",
                            IngredientName = "심해석"
                        },
                        new
                        {
                            IngredientNum = 5,
                            CountryNum = 0,
                            Description_I = "정제된 고순도 수자원, 생명 유지나 에너지 전환에 사용",
                            IngredientName = "청류정수"
                        },
                        new
                        {
                            IngredientNum = 6,
                            CountryNum = 0,
                            Description_I = "수중 생명체 뼈대에서 채취한 반투명 결정체",
                            IngredientName = "바다수정"
                        },
                        new
                        {
                            IngredientNum = 7,
                            CountryNum = 0,
                            Description_I = "대기 중에서 응결되는 가벼운 결정, 부유 장치 제작에 활용",
                            IngredientName = "풍정석"
                        },
                        new
                        {
                            IngredientNum = 8,
                            CountryNum = 0,
                            Description_I = "고속 회전에너지로 저장된 압축 에너지 컨테이너",
                            IngredientName = "회오리 플라스크"
                        },
                        new
                        {
                            IngredientNum = 9,
                            CountryNum = 0,
                            Description_I = "대기 진동과 공명하는 음파 기반의 마력 결정",
                            IngredientName = "공명결정"
                        },
                        new
                        {
                            IngredientNum = 10,
                            CountryNum = 0,
                            Description_I = "용암 지대에서 채굴되는 고열 금속 결정",
                            IngredientName = "화염정광"
                        },
                        new
                        {
                            IngredientNum = 11,
                            CountryNum = 0,
                            Description_I = "천연 용암석으로 이루어진 고열 연료 자원",
                            IngredientName = "용석탄"
                        },
                        new
                        {
                            IngredientNum = 12,
                            CountryNum = 0,
                            Description_I = "마그마 생물의 분비물로 형성된 진귀한 에너지 진주",
                            IngredientName = "발화진주"
                        });
                });

            modelBuilder.Entity("DB.Models.Product", b =>
                {
                    b.Property<int>("ProductNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description_P")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Receipt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductNum");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductNum = 1,
                            Description_P = "고온, 고압의 핵융합 에너지 결정. 무기 코어나 동력 장치에 사용됨",
                            ProductName = "플라즈마 하트(Plasma Heart)",
                            Receipt = "화염정광 + 심해석 + 풍정석 + 암철석"
                        },
                        new
                        {
                            ProductNum = 2,
                            Description_P = "공중 부양 능력이 있는 에너지 광물. 공중 장비나 비행체에 쓰임",
                            ProductName = "천공핵(Skycore Crystal)",
                            Receipt = "용석탄 + 청류정수 + 공명결정 + 석기정"
                        },
                        new
                        {
                            ProductNum = 3,
                            Description_P = "대지와 불의 융합체로, 강력한 지진 및 폭발 효과를 가진 전술 병기 코어",
                            ProductName = "지화탄(Geomagma Capsule)",
                            Receipt = "발화진주 + 바다수정 + 회오리 플라스크 + 진토금"
                        },
                        new
                        {
                            ProductNum = 4,
                            Description_P = "원소의 핵심 에너지 덩어리. 고급 마법 무기나 장비에 필수",
                            ProductName = "에테르 코어(Aether Core)",
                            Receipt = "용석탄 + 청류정수 + 풍정석 + 암철석"
                        },
                        new
                        {
                            ProductNum = 5,
                            Description_P = "강한 자기력을 가진 금속 합성체. 방어구 또는 에너지 실드용",
                            ProductName = "마그네실(Magnesyl Alloy)",
                            Receipt = "화염정광 + 심해석 + 공명결정 + 진토금"
                        },
                        new
                        {
                            ProductNum = 6,
                            Description_P = "냉각 및 연료 안정화에 사용되는 특수 결정. 에너지 장치 필수 자원",
                            ProductName = "플루오라이트(Fluorite X)",
                            Receipt = "발화진주 + 청류정수 + 회오리 플라스크 + 석기정"
                        },
                        new
                        {
                            ProductNum = 7,
                            Description_P = "생명 에너지와 기술이 융합된 생체 동력 코어",
                            ProductName = "제네시움(Genesium)",
                            Receipt = "화염정광 + 바다수정 + 공명결정 + 석기정"
                        });
                });

            modelBuilder.Entity("DB.Models.Ingredient", b =>
                {
                    b.HasOne("DB.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
